//<auto-generated>
namespace VehicleRepository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class added_Entities_location : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Locationinfoes",
                c => new
                    {
                        locationID = c.Long(nullable: false, identity: true),
                        ID = c.Long(nullable: false),
                        lat = c.Double(nullable: false),
                        lon = c.Double(nullable: false),
                    })
                .PrimaryKey(t => t.locationID)
                .ForeignKey("dbo.Logins", t => t.ID, cascadeDelete: true)
                .Index(t => t.ID);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Locationinfoes", "ID", "dbo.Logins");
            DropIndex("dbo.Locationinfoes", new[] { "ID" });
            DropTable("dbo.Locationinfoes");
        }
    }
}
